name: Manual APK Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of APK to build'
        required: true
        default: 'both'
        type: choice
        options:
        - debug
        - release
        - both

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      if: ${{ inputs.build_type == 'debug' || inputs.build_type == 'both' }}
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      if: ${{ inputs.build_type == 'release' || inputs.build_type == 'both' }}
      run: ./gradlew assembleRelease
      
    - name: Upload Debug APK
      if: ${{ inputs.build_type == 'debug' || inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Release APK
      if: ${{ inputs.build_type == 'release' || inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Create Build Summary
      run: |
        echo "## 📱 Manual APK Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Build Type**: ${{ inputs.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "**Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "**Time**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ inputs.build_type }}" = "debug" ] || [ "${{ inputs.build_type }}" = "both" ]; then
          echo "✅ **Debug APK**: Built successfully" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ inputs.build_type }}" = "release" ] || [ "${{ inputs.build_type }}" = "both" ]; then
          echo "✅ **Release APK**: Built successfully" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📥 Download Instructions:" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to the **Actions** tab" >> $GITHUB_STEP_SUMMARY
        echo "2. Click on this workflow run" >> $GITHUB_STEP_SUMMARY
        echo "3. Scroll down to **Artifacts**" >> $GITHUB_STEP_SUMMARY
        echo "4. Download the APK file(s)" >> $GITHUB_STEP_SUMMARY